version: '3.7'

services:
  web:
#    build: ./app
    container_name: ibst_web_app
    image: ibst:latest
    command: gunicorn -w 4 --bind 0.0.0.0:8000  BOSS:app
#    command: flask run --host=0.0.0.0 --port=8000 --cert=adhoc 
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
