"""URL-imagenes

Revision ID: 4caa5aeedba7
Revises: b26a8d3d0de9
Create Date: 2020-05-03 23:00:27.055140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4caa5aeedba7'
down_revision = 'b26a8d3d0de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pictures', sa.Column('picture_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pictures', 'picture_url')
    # ### end Alembic commands ###
