"""empty message

Revision ID: 4edbf64c4157
Revises: c191141e5d8a
Create Date: 2020-02-15 23:51:56.450696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4edbf64c4157'
down_revision = 'c191141e5d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_shortener',
    sa.Column('shortcutlink', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shortcutlink')
    )
    op.create_index(op.f('ix_url_shortener_expiration_date'), 'url_shortener', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_url_shortener_shortcutlink'), 'url_shortener', ['shortcutlink'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_shortener_shortcutlink'), table_name='url_shortener')
    op.drop_index(op.f('ix_url_shortener_expiration_date'), table_name='url_shortener')
    op.drop_table('url_shortener')
    # ### end Alembic commands ###
