"""empty message

Revision ID: 82de32e5b69a
Revises: 8c268d37eddf
Create Date: 2020-02-10 21:57:31.315303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82de32e5b69a'
down_revision = '8c268d37eddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Imagen', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Imagen')
    # ### end Alembic commands ###
