"""empty message

Revision ID: c191141e5d8a
Revises: 82de32e5b69a
Create Date: 2020-02-12 16:38:00.525604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c191141e5d8a'
down_revision = '82de32e5b69a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Telefono', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('Twitter', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'Twitter')
    op.drop_column('user', 'Telefono')
    # ### end Alembic commands ###
