"""Tabla-imagenes

Revision ID: f3f7bdddb742
Revises: 
Create Date: 2020-03-23 18:13:46.846647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f7bdddb742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id_branch', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_branch'),
    sa.UniqueConstraint('type')
    )
    op.create_table('membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('poll',
    sa.Column('id_poll', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_poll'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_poll_start_date'), 'poll', ['start_date'], unique=False)
    op.create_table('url_shortener',
    sa.Column('shortcutlink', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=2048), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('shortcutlink')
    )
    op.create_index(op.f('ix_url_shortener_expiration_date'), 'url_shortener', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_url_shortener_shortcutlink'), 'url_shortener', ['shortcutlink'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Usuario', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('Nombre', sa.String(length=30), nullable=True),
    sa.Column('Apellidos', sa.String(length=200), nullable=True),
    sa.Column('Telefono', sa.String(length=15), nullable=True),
    sa.Column('Campus', sa.String(length=30), nullable=True),
    sa.Column('Escuela', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_Usuario'), 'user', ['Usuario'], unique=True)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('id_Membresia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_Membresia'], ['membresia.id'], )
    )
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_picture', sa.String(length=50), nullable=True),
    sa.Column('large_picture', sa.String(length=50), nullable=True),
    sa.Column('medium_picture', sa.String(length=50), nullable=True),
    sa.Column('small_picture', sa.String(length=50), nullable=True),
    sa.Column('Twitter_user_picture', sa.String(length=50), nullable=True),
    sa.Column('last_changed', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poll_option',
    sa.Column('id_option', sa.Integer(), nullable=False),
    sa.Column('id_parent_poll', sa.Integer(), nullable=True),
    sa.Column('option_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_parent_poll'], ['poll.id_poll'], ),
    sa.PrimaryKeyConstraint('id_option')
    )
    op.create_table('post',
    sa.Column('id_post', sa.Integer(), nullable=False),
    sa.Column('id_autor', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('Asunto', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['id_autor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_post')
    )
    op.create_index(op.f('ix_post_date'), 'post', ['date'], unique=False)
    op.create_table('Topic',
    sa.Column('id_post', sa.Integer(), nullable=True),
    sa.Column('id_branch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_branch'], ['branch.id_branch'], ),
    sa.ForeignKeyConstraint(['id_post'], ['post.id_post'], )
    )
    op.create_table('option_vote',
    sa.Column('id_option', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_option'], ['poll_option.id_option'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option_vote')
    op.drop_table('Topic')
    op.drop_index(op.f('ix_post_date'), table_name='post')
    op.drop_table('post')
    op.drop_table('poll_option')
    op.drop_table('pictures')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_Usuario'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_url_shortener_shortcutlink'), table_name='url_shortener')
    op.drop_index(op.f('ix_url_shortener_expiration_date'), table_name='url_shortener')
    op.drop_table('url_shortener')
    op.drop_index(op.f('ix_poll_start_date'), table_name='poll')
    op.drop_table('poll')
    op.drop_table('membresia')
    op.drop_table('branch')
    # ### end Alembic commands ###
