"""empty message

Revision ID: 43ae5b5ee547
Revises: 8e2178bb6f6f
Create Date: 2020-03-23 18:05:28.776009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ae5b5ee547'
down_revision = '8e2178bb6f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pictures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_picture', sa.String(length=50), nullable=True),
    sa.Column('large_picture', sa.String(length=50), nullable=True),
    sa.Column('medium_picture', sa.String(length=50), nullable=True),
    sa.Column('small_picture', sa.String(length=50), nullable=True),
    sa.Column('Twitter_user_picture', sa.String(length=50), nullable=True),
    sa.Column('last_changed', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('user', 'Twitter')
    op.drop_column('user', 'Imagen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('Imagen', sa.VARCHAR(length=50), nullable=True))
    op.add_column('user', sa.Column('Twitter', sa.VARCHAR(length=50), nullable=True))
    op.drop_table('pictures')
    # ### end Alembic commands ###
